---
title: "MCMC Taken from Statistical Rethinking Ch 8"
output: html_notebook
---



```{r}
library(rethinking)
#rstan_options(auto_write = TRUE)
#options(mc.cores = parallel::detectCores())
```

```{r}
data(rugged)
d <- rugged
d$log_gdp <- log(d$rgdppc_2000)
dd <- d[ complete.cases(d$rgdppc_2000) , ]
```

```{r}
## R code 8.3
#Create a function for the PD from this data set given
#the below regression 
m8.1 <- map(
  alist(
    log_gdp ~ dnorm( mu , sigma ) ,
    mu <- a + bR*rugged + bA*cont_africa + bAR*rugged*cont_africa ,
    a ~ dnorm(0,100),
    bR ~ dnorm(0,10),
    bA ~ dnorm(0,10),
    bAR ~ dnorm(0,10),
    sigma ~ dunif(0,10)
  ) ,
  data=dd )
```

```{r}
#Review Model
precis(m8.1)
```

```{r}
## R code 8.4
#Simplify the data set
dd.trim <- dd[ , c("log_gdp","rugged","cont_africa") ]
str(dd.trim)
```

```{r}
## R code 8.5
#Remap (to STAN) the regression function 
#sigma to a uniform prior
#using a Hamiltonian MCMC to sample from the PD
m8.1stan <- map2stan(
  alist(
    log_gdp ~ dnorm( mu , sigma ) ,
    mu <- a + bR*rugged + bA*cont_africa + bAR*rugged*cont_africa ,
    a ~ dnorm(0,100),
    bR ~ dnorm(0,10),
    bA ~ dnorm(0,10),
    bAR ~ dnorm(0,10),
    sigma ~ dcauchy(0,2)
  ) ,
  data=dd.trim,iter=2000,warmup = 1000 )
```

```{r}
#View MCMC model via STAN
print(m8.1stan)
```

```{r}
## R code 8.6
#Updated Regression output
precis(m8.1stan)
```

```{r}
## R code 8.7
#Using 4 Chains
m8.1stan_4chains <- map2stan( m8.1stan , chains=4 , cores=4 )
precis(m8.1stan_4chains)
```


```{r}
## R code 8.8
#extact sampled values
post <- extract.samples( m8.1stan )
str(post)

```

```{r}
## R code 8.9
pairs(post)
```

```{r}
#PD of each parameter
dens(post$a)
dens(post$bR)
```

```{r}
## R code 8.10
pairs(m8.1stan)
```

```{r}
## R code 8.11
show(m8.1stan)
```

